let colombia = [
  { name: "Luis", salary: 1500 },
  { name: "Maria", salary: 800 },
  { name: "Mayela", salary: 750 },
  { name: "Teresa", salary: 1200 },
  { name: "Nelson", salary: 1800 },
  { name: "Olga", salary: 2200 },
  { name: "Jose", salary: 450 },
  { name: "Pablo", salary: 550 },
  { name: "Ramon", salary: 600 },
  { name: "Alexei", salary: 850 },
  { name: "Alain", salary: 650 },
  { name: "Magdey", salary: 420 },
  { name: "Yudenis", salary: 350 },
  { name: "Alain", salary: 950 },
  { name: "Yaneisi", salary: 1150 },
  { name: "Alessandro", salary: 400 },
  { name: "Alejandro", salary: 400 },
  { name: "Emilia", salary: 1250 },
  { name: "Veronica", salary: 1450 },
  { name: "Rafael", salary: 1300 },
  { name: "Carlos", salary: 1350 },
];
